setwd("~/Documents/Roberts Lab/O.lurida_Stress/Data")
Histo <- read.csv("2017-Oly-Histo-Results.csv", header=T, stringsAsFactors = T)
Histo$Stage <- as.factor(Histo$Stage)
library(plyr)

# All Populations Combined ------------------------------------------------
All.6 <- subset(Histo, Phase %in% "TEMP" & Treatment %in% "6")
All.10 <- subset(Histo, Phase %in% "TEMP" & Treatment %in% "10")
All.6.Low <- subset(Histo, Phase %in% "OA" & Treatment %in% "6-Low")
All.6.Amb <- subset(Histo, Phase %in% "OA" & Treatment %in% "6-Amb")
All.10.Low <- subset(Histo, Phase %in% "OA" & Treatment %in% "10-Low")
All.10.Amb <- subset(Histo, Phase %in% "OA" & Treatment %in% "10-Amb")
Allp.6 <- data.frame(unclass(100*prop.table(table(All.6$Stage))))
Allp.10 <- data.frame(unclass(100*prop.table(table(All.10$Stage))))
Allp.6.Low <- data.frame(unclass(100*prop.table(table(All.6.Low$Stage))))
Allp.6.Amb <- data.frame(unclass(100*prop.table(table(All.6.Amb$Stage))))
Allp.10.Low <- data.frame(unclass(100*prop.table(table(All.10.Low$Stage))))
Allp.10.Amb <- data.frame(unclass(100*prop.table(table(All.10.Amb$Stage))))
All.p <- data.frame(cbind(Allp.6, Allp.10, Allp.6.Low, Allp.6.Amb, Allp.10.Low, Allp.10.Amb))
colnames(All.p) <- c("6", "10", "6.Low", "6.Amb", "10.Low", "10.Amb")
Stages <- c("Stage 1", "Stage 2", "Stage 3")
png(filename = "~/Documents/Roberts Lab/O.lurida_Stress/Analyses/Gonad-Stage-Pie-Charts.png", width = 600, height = 800)
par(mfrow = c(3, 2), mar=c(.5,1,2,0.5), oma=c(1,2,3,1), cex.main= 1.3, cex=.75)
pie(table(All.6$Stage), main="6 DegC", radius=1, labels=paste(Stages, "\n", "n=", table(All.6$Stage), "\n", round(All.p$`6`), "%", sep=""))
pie(table(All.10$Stage), main="10 DegC", radius=1, labels=paste(Stages, "\n", "n=", table(All.10$Stage),"\n", round(All.p$`10`), "%", sep=""))
pie(table(All.6.Low$Stage), main="6 DegC, Low pH", radius=1, labels=paste(Stages, "\n", "n=", table(All.6.Low$Stage), "\n", round(All.p$`6.Low`), "%", sep=""))
pie(table(All.10.Low$Stage), main="10 DegC, Low pH", radius=1, labels=paste(Stages, "\n", "n=", table(All.10.Low$Stage),"\n", round(All.p$`10.Low`), "%", sep=""))
pie(table(All.6.Amb$Stage), main="6 DegC, Amb pH", radius=1, labels=paste(Stages, "\n", "n=", table(All.6.Amb$Stage), "\n", round(All.p$`6.Amb`), "%", sep=""))
pie(table(All.10.Amb$Stage), main="10 DegC, Amp pH", radius=1, labels=paste(Stages, "\n", "n=", table(All.10.Amb$Stage), "\n", round(All.p$`10.Amb`), "%", sep=""))
title("Gonad Stage by Treatment, all Populations \nOstrea lurida 2016-2017 Experiment", outer=TRUE) 
dev.off()

# Each Population Separately ----------------------------------------------

Pops <- levels(Histo$Population)
Pop.names <- c("Hood Canal", "South Sound F2", "Fidalgo Bay", "South Sound F1")
for (i in 1:length(Pops)) {
  T <- Pops[i]
  T.6 <- subset(Histo, Population %in% T & Phase %in% "TEMP" & Treatment %in% "6")
  T.10 <- subset(Histo, Population %in% T & Phase %in% "TEMP" & Treatment %in% "10")
  T.6.Low <- subset(Histo, Population %in% T & Phase %in% "OA" & Treatment %in% "6-Low")
  T.6.Amb <- subset(Histo, Population %in% T & Phase %in% "OA" & Treatment %in% "6-Amb")
  T.10.Low <- subset(Histo, Population %in% T & Phase %in% "OA" & Treatment %in% "10-Low")
  T.10.Amb <- subset(Histo, Population %in% T & Phase %in% "OA" & Treatment %in% "10-Amb")
  Tp.6 <- data.frame(unclass(100*prop.table(table(T.6$Stage))))
  Tp.10 <- data.frame(unclass(100*prop.table(table(T.10$Stage))))
  Tp.6.Low <- data.frame(unclass(100*prop.table(table(T.6.Low$Stage))))
  Tp.6.Amb <- data.frame(unclass(100*prop.table(table(T.6.Amb$Stage))))
  Tp.10.Low <- data.frame(unclass(100*prop.table(table(T.10.Low$Stage))))
  Tp.10.Amb <- data.frame(unclass(100*prop.table(table(T.10.Amb$Stage))))
  T.p <- data.frame(cbind(Tp.6, Tp.10, Tp.6.Low, Tp.6.Amb, Tp.10.Low, Tp.10.Amb))
  colnames(T.p) <- c("6", "10", "6.Low", "6.Amb", "10.Low", "10.Amb")
  Stages <- c("Stage 1", "Stage 2", "Stage 3")
  filename <- paste("~/Documents/Roberts Lab/O.lurida_Stress/Analyses/Gonad-Stage-Pie-Charts-", T, ".png", sep="")
  png(filename = filename, width = 600, height = 800)
  par(mfrow = c(3, 2), mar=c(.5,1,2,0.5), oma=c(1,2,3,1), cex.main= 1.3, cex=.75)
  pie(table(T.6$Stage), main="6 DegC", radius=1, labels=paste(Stages, "\n", "n=", table(T.6$Stage), "\n", round(T.p$`6`), "%", sep=""))
  pie(table(T.10$Stage), main="10 DegC", radius=1, labels=paste(Stages, "\n", "n=", table(T.10$Stage), ", ", round(T.p$`10`), "%", sep=""))
  pie(table(T.6.Low$Stage), main="6 DegC, Low pH", radius=1, labels=paste(Stages, "\n", "n=", table(T.6.Low$Stage), "\n", round(T.p$`6.Low`), "%", sep=""))
  pie(table(T.10.Low$Stage), main="10 DegC, Low pH", radius=1, labels=paste(Stages, "\n", "n=", table(T.10.Low$Stage), "\n", round(T.p$`10.Low`), "%", sep=""))
  pie(table(T.6.Amb$Stage), main="6 DegC, Amb pH", radius=1, labels=paste(Stages, "\n", "n=", table(T.6.Amb$Stage), "\n", round(T.p$`6.Amb`), "%", sep=""))
  pie(table(T.10.Amb$Stage), main="10 DegC, Amb pH", radius=1, labels=paste(Stages, "\n", "n=", table(T.10.Amb$Stage), "\n", round(T.p$`10.Amb`), "%", sep=""))
  title(paste("Gonad Stage by Treatment ", Pop.names[i], "\n", "Ostrea lurida 2016-2017 Experiment", sep=""), outer=TRUE)
  dev.off()
}


### boneyard

# Histo$Stage <- as.factor(Histo$Stage)
# counts.temp <- count(df=subset(Histo, Phase %in% "TEMP"), c("Phase", "Treatment", "Stage"))
# counts.OA <- count(df=subset(Histo, Phase %in% "OA"), c("Phase", "Treatment", "Stage"))
# counts.all <- count(df=Histo, c("Phase", "Treatment", "Stage"))
