setwd("~/Documents/Roberts Lab/O.lurida_Stress/Data")
Histo <- read.csv("2017-Oly-Histo-Results.csv", header=T, stringsAsFactors = F)
library(plyr)
table(Histo$Stage)
table(Histo$Sex)
# Histo$Stage <- as.factor(Histo$Stage)

counts.temp <- count(df=subset(Histo, Phase %in% "TEMP"), c("Phase", "Treatment", "Stage"))
counts.OA <- count(df=subset(Histo, Phase %in% "OA"), c("Phase", "Treatment", "Stage"))
counts.all <- count(df=Histo, c("Phase", "Treatment", "Stage"))
# counts.temp$percent <- 

Histo.6 <- subset(Histo, Phase %in% "TEMP" & Treatment %in% "6")
Histo.10 <- subset(Histo, Phase %in% "TEMP" & Treatment %in% "10")
Histo.6.Low <- subset(Histo, Phase %in% "OA" & Treatment %in% "6-Low")
Histo.6.Amb <- subset(Histo, Phase %in% "OA" & Treatment %in% "6-Amb")
Histo.10.Low <- subset(Histo, Phase %in% "OA" & Treatment %in% "10-Low")
Histo.10.Amb <- subset(Histo, Phase %in% "OA" & Treatment %in% "10-Amb")
Pct.6 <- data.frame(unclass(100*prop.table(table(Histo.6$Stage))))
Pct.10 <- data.frame(unclass(100*prop.table(table(Histo.10$Stage))))
Pct.6.Low <- data.frame(unclass(100*prop.table(table(Histo.6.Low$Stage))))
Pct.6.Amb <- data.frame(unclass(100*prop.table(table(Histo.6.Amb$Stage))))
Pct.10.Low <- data.frame(unclass(100*prop.table(table(Histo.10.Low$Stage))))
Pct.10.Amb <- data.frame(unclass(100*prop.table(table(Histo.10.Amb$Stage))))
stage.stats <- data.frame(cbind(Pct.6, Pct.10, Pct.6.Low, Pct.6.Amb, Pct.10.Low, Pct.10.Amb))
colnames(stage.stats) <- c("6", "10", "6.Low", "6.Amb", "10.Low", "10.Amb")
Stages <- c("Stage 1", "Stage 2", "Stage 3")

png(filename = "~/Documents/Roberts Lab/O.lurida_Stress/Analyses/Gonad-Stage-Pie-Charts.png", width = 600, height = 800)
par(mfrow = c(3, 2), mar=c(.5,1,2,0.5), oma=c(1,2,3,1))
pie(table(Histo.6$Stage), main="6 DegC", radius=1, labels=paste(Stages, "\n", table(Histo.6$Stage), ", ", round(stage.stats$`6`), "%", sep=""))
pie(table(Histo.10$Stage), main="10 DegC", radius=1, labels=paste(Stages, "\n", table(Histo.10$Stage), ", ", round(stage.stats$`10`), "%", sep=""))
pie(table(Histo.6.Low$Stage), main="6 DegC, Low pH", radius=1, labels=paste(Stages, "\n", table(Histo.6.Low$Stage), ", ", round(stage.stats$`6.Low`), "%", sep=""))
pie(table(Histo.10.Low$Stage), main="10 DegC, Low pH", radius=1, labels=paste(Stages, "\n", table(Histo.10.Low$Stage), ", ", round(stage.stats$`10.Low`), "%", sep=""))
pie(table(Histo.6.Amb$Stage), main="6 DegC, Amb pH", radius=1, labels=paste(Stages, "\n", table(Histo.6.Amb$Stage), ", ", round(stage.stats$`6.Amb`), "%", sep=""))
pie(table(Histo.10.Amb$Stage), main="10 DegC, Amp pH", radius=1, labels=paste(Stages, "\n", table(Histo.10.Amb$Stage), ", ", round(stage.stats$`10.Amb`), "%", sep=""))
title("Gonad Stage by Treatment, all Populations \nOstrea lurida 2016-2017 Experiment", outer=TRUE) 
dev.off()
